[auth]
usuario = "JAcamilo"
password = "CamiloBOSS"

type = "service_account"
project_id = "gestoroperacionesce"
private_key_id = "4d82a0715f4a244a9b5cf37e8b0c88e192883b8d"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCKsfuwvztUI+NO
7wf045LosXDbr6vwU8QdbYSo4WNcWLyGorQbxRoUD74AZhSM1Tz0FqgK3DwcttNL
sxd9RpcKbDIW6/xTusS0a3jirGmArxnGoghhGQ7Vk8dBJRVc5NmFVQ+sSj0Sb159
Dsiyl4Jz4rl5oBcTEnjjMP4xMx56GqxJYR8jGH8P4rZYY4W6u+I/oWbRJQbhX9oG
QwekHVLIGRvH7XgWOOi7OVNjwRK13+2dRuTmqA5jnuJ/2NaOF5goOh0Kue7/AgZP
e9mkLY8WmumSnGKPehk0PVnvLzHb/tPqiRa3Zu5EtHYKRhh1b2GyI4AneQMSNR2h
a/tWXIYVAgMBAAECggEAA1f/JWe22nRzCnggzPqflBSTD/jQQF8En2EAjcHBT3yk
LurFRNYfptQqVIAhhrOtYIUbUAe3O0n9FhofOtn00j+BhaPy1WHvVBozM+PMN1oB
WRSW9yBPhz6k0yE9vpuV0u0WD6VKi6M7t/AfTo7wijKxHgmKBN+xImkP98evuGnb
H4NwzVMF/Ny2TUVi6IFkHtw3l1sl4d82Kq2jPMA+86kacmhKMBLHjCAuGSyVgg19
sunclCoXM2JFfA7EwctAY1EHvuZcbtsgCPL7A40IFWsMFLz5Nu6C0pKvC28CPYkt
EfGLF+QIhgZGVvD6Gy8XJxiUMzxibwbCYlO4MHyoEQKBgQC9UKfdvlJylLjqZN2S
cV0E69O9yMggOG5DinsTR9mokMQrxsnJ3A7jShgAwBrkFo1HFJKNbt3AVIIQK2Oy
+HQuHTdsbunoOYH61D8h7S4KgZUOJWmYKyi4gpi65KUKrKHUoY7WX2knT575K7ih
QqS5agi8sA73Hgf9xSZPJKdspwKBgQC7jLk0TsQ3RjrIY7H9/3BDCd13MrGaBMv9
357QU+w4KlxfjqFQ13775dUiddjykd/6EtI8kUgjsYwngHzIwlsfGGQOmDsSPXhy
hHhZVHq3YpyfMBskfklQ9r7uaiA9x8L5mEVDWhO+2MMespeqX1EVdN30wI4R4dYM
47Vi7N8i4wKBgEM5qOJs+woFFcTmHGgsKUPeGkqCSc5nO4BwZFPsZ7Yb8g05gd5U
blT3sp5RmTr1ZyWegIwImmX5nFXxkm2zHE5jwZKXsCfug+F2DRUXDApfCXcEggKv
EL60YVe8aX7o3m6LEBW/u69h7qm8hMt+xs+wf3nBaw8FcwECSSBBe9JxAoGADgXD
gymwegGCO6FYmYkTt69xI4xiwwVAy0aA9UqRCtH//hUH8qdqEyNoAB+XjOtjN6tY
lLa4EhMgS4PL0KbXcUe9k2nGYOK/srA831D1q+hvlWdfYCchDDCmreS5bGUXKto7
s4F0oHxMemsX8+EUiuol/jq3ZJbiDiyoTzEurckCgYEAi200umoiGzKTSCz0+SWO
eI+vUm9bFHVmRCnIH+ovH/dkI1aS94yHZhpXjz5kIGceTeLCG8EtezO4bpfrshVz
zuEv4zSyuAtwG+bw0o75zADcERrIK4ZoJOgyD/eOTIDDoxzrsxNT2IGHx7kHXRgq
1Mykm2cdB7VPFfEsR7VFwO8=
-----END PRIVATE KEY-----"""
client_email = "operaciones-ce-sa@gestoroperacionesce.iam.gserviceaccount.com"
client_id = "109625281328766436582"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/operaciones-ce-sa%40gestoroperacionesce.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[gsheets]
spreadsheet_url = "https://docs.google.com/spreadsheets/d/1a6kY8YBMdEFJUnP381LwTOZwSuFzXtODZ8CyLcuBcO8/edit?gid=0"
